#cloud-config
package_update: true
packages:
  - snapd
runcmd:
  - snap install microk8s --classic
  - usermod -a -G microk8s ubuntu
  - microk8s status --wait-ready
  - microk8s enable dns storage
  - echo "MicroK8s installed and ready"
